export const PERMISSION_VIDEOHUB_SCENES_SCHEDULE: string = "PERMISSION_VIDEOHUB_SCENES_SCHEDULE";
export const PERMISSION_VIDEOHUB_SCENES_EDIT: string = "PERMISSION_VIDEOHUB_SCENES_EDIT";
export const PERMISSION_USER_EDIT: string = "PERMISSION_USER_EDIT", PERMISSION_ROLE_EDIT: string = "PERMISSION_ROLE_EDIT";
export const PERMISSION_VIDEOHUB_EDIT: string = "PERMISSION_VIDEOHUB_EDIT";
export const TOGGLEABLE_PERMISSIONS: string[] = [PERMISSION_VIDEOHUB_EDIT, PERMISSION_VIDEOHUB_SCENES_EDIT, PERMISSION_VIDEOHUB_SCENES_SCHEDULE];


